import type { Exercise } from "./schema";

export const EXERCISE_CATALOG: Exercise[] = [
  {
    id: "ex-bench-barbell",
    name: "Supino reto",
    primaryMuscle: "chest",
    secondaryMuscles: ["shoulders_front", "triceps"],
    equipment: "barbell",
    movementPattern: "push_h",
    isUnilateral: false,
    baseExerciseId: null,
    variationType: null,
    equipmentDetail: null,
    muscleEmphasis: "mid_range",
    difficultyLevel: "intermediate",
    requiresSpotter: true,
    riskFlags: [],
    ownerCoachId: null,
    instructions: null,
  },
  {
    id: "ex-incline-db",
    name: "Supino inclinado halteres",
    primaryMuscle: "chest",
    secondaryMuscles: ["shoulders_front", "triceps"],
    equipment: "dumbbell",
    movementPattern: "push_h",
    isUnilateral: false,
    baseExerciseId: "ex-bench-barbell",
    variationType: "incline-30",
    equipmentDetail: null,
    muscleEmphasis: "stretch",
    difficultyLevel: "intermediate",
    requiresSpotter: false,
    riskFlags: [],
    ownerCoachId: null,
    instructions: null,
  },
  {
    id: "ex-cable-crossover",
    name: "Crossover",
    primaryMuscle: "chest",
    secondaryMuscles: [],
    equipment: "cable",
    movementPattern: "isolation",
    isUnilateral: false,
    baseExerciseId: null,
    variationType: null,
    equipmentDetail: "cable-low-pulley",
    muscleEmphasis: "peak",
    difficultyLevel: "beginner",
    requiresSpotter: false,
    riskFlags: [],
    ownerCoachId: null,
    instructions: null,
  },
  {
    id: "ex-shoulder-press-machine",
    name: "Desenvolvimento máquina",
    primaryMuscle: "shoulders_front",
    secondaryMuscles: ["triceps", "shoulders_side"],
    equipment: "machine",
    movementPattern: "push_v",
    isUnilateral: false,
    baseExerciseId: null,
    variationType: null,
    equipmentDetail: null,
    muscleEmphasis: null,
    difficultyLevel: "beginner",
    requiresSpotter: false,
    riskFlags: [],
    ownerCoachId: null,
    instructions: null,
  },
  {
    id: "ex-lateral-raise",
    name: "Elevação lateral",
    primaryMuscle: "shoulders_side",
    secondaryMuscles: [],
    equipment: "dumbbell",
    movementPattern: "isolation",
    isUnilateral: false,
    baseExerciseId: null,
    variationType: null,
    equipmentDetail: null,
    muscleEmphasis: "peak",
    difficultyLevel: "beginner",
    requiresSpotter: false,
    riskFlags: [],
    ownerCoachId: null,
    instructions: null,
  },
  {
    id: "ex-tricep-rope",
    name: "Tríceps corda",
    primaryMuscle: "triceps",
    secondaryMuscles: [],
    equipment: "cable",
    movementPattern: "isolation",
    isUnilateral: false,
    baseExerciseId: null,
    variationType: null,
    equipmentDetail: null,
    muscleEmphasis: "peak",
    difficultyLevel: "beginner",
    requiresSpotter: false,
    riskFlags: [],
    ownerCoachId: null,
    instructions: null,
  },
  {
    id: "ex-lat-pulldown",
    name: "Puxada frontal",
    primaryMuscle: "back_lats",
    secondaryMuscles: ["biceps", "back_upper"],
    equipment: "cable",
    movementPattern: "pull_v",
    isUnilateral: false,
    baseExerciseId: null,
    variationType: null,
    equipmentDetail: null,
    muscleEmphasis: "stretch",
    difficultyLevel: "beginner",
    requiresSpotter: false,
    riskFlags: [],
    ownerCoachId: null,
    instructions: null,
  },
  {
    id: "ex-row-barbell",
    name: "Remada curvada",
    primaryMuscle: "back_upper",
    secondaryMuscles: ["back_lats", "biceps"],
    equipment: "barbell",
    movementPattern: "pull_h",
    isUnilateral: false,
    baseExerciseId: null,
    variationType: null,
    equipmentDetail: null,
    muscleEmphasis: "mid_range",
    difficultyLevel: "intermediate",
    requiresSpotter: false,
    riskFlags: ["joelho_direito"],
    ownerCoachId: null,
    instructions: null,
  },
  {
    id: "ex-row-seated",
    name: "Remada sentada",
    primaryMuscle: "back_upper",
    secondaryMuscles: ["back_lats", "biceps"],
    equipment: "cable",
    movementPattern: "pull_h",
    isUnilateral: false,
    baseExerciseId: "ex-row-barbell",
    variationType: "seated",
    equipmentDetail: null,
    muscleEmphasis: "mid_range",
    difficultyLevel: "beginner",
    requiresSpotter: false,
    riskFlags: [],
    ownerCoachId: null,
    instructions: null,
  },
  {
    id: "ex-bicep-curl-db",
    name: "Rosca direta halteres",
    primaryMuscle: "biceps",
    secondaryMuscles: ["forearms"],
    equipment: "dumbbell",
    movementPattern: "isolation",
    isUnilateral: false,
    baseExerciseId: null,
    variationType: null,
    equipmentDetail: null,
    muscleEmphasis: "peak",
    difficultyLevel: "beginner",
    requiresSpotter: false,
    riskFlags: [],
    ownerCoachId: null,
    instructions: null,
  },
  {
    id: "ex-face-pull",
    name: "Face pull",
    primaryMuscle: "shoulders_rear",
    secondaryMuscles: ["back_upper"],
    equipment: "cable",
    movementPattern: "pull_h",
    isUnilateral: false,
    baseExerciseId: null,
    variationType: null,
    equipmentDetail: null,
    muscleEmphasis: "peak",
    difficultyLevel: "beginner",
    requiresSpotter: false,
    riskFlags: [],
    ownerCoachId: null,
    instructions: null,
  },
  {
    id: "ex-squat-barbell",
    name: "Agachamento livre",
    primaryMuscle: "quads",
    secondaryMuscles: ["glutes", "hamstrings"],
    equipment: "barbell",
    movementPattern: "squat",
    isUnilateral: false,
    baseExerciseId: null,
    variationType: null,
    equipmentDetail: null,
    muscleEmphasis: "stretch",
    difficultyLevel: "intermediate",
    requiresSpotter: true,
    riskFlags: [],
    ownerCoachId: null,
    instructions: null,
  },
  {
    id: "ex-rdl",
    name: "Stiff com barra",
    primaryMuscle: "hamstrings",
    secondaryMuscles: ["glutes", "back_lower"],
    equipment: "barbell",
    movementPattern: "hinge",
    isUnilateral: false,
    baseExerciseId: null,
    variationType: null,
    equipmentDetail: null,
    muscleEmphasis: "stretch",
    difficultyLevel: "intermediate",
    requiresSpotter: false,
    riskFlags: [],
    ownerCoachId: null,
    instructions: null,
  },
  {
    id: "ex-leg-press",
    name: "Leg press",
    primaryMuscle: "quads",
    secondaryMuscles: ["glutes"],
    equipment: "machine",
    movementPattern: "squat",
    isUnilateral: false,
    baseExerciseId: null,
    variationType: null,
    equipmentDetail: null,
    muscleEmphasis: "stretch",
    difficultyLevel: "beginner",
    requiresSpotter: false,
    riskFlags: [],
    ownerCoachId: null,
    instructions: null,
  },
  {
    id: "ex-leg-curl",
    name: "Flexora sentada",
    primaryMuscle: "hamstrings",
    secondaryMuscles: [],
    equipment: "machine",
    movementPattern: "isolation",
    isUnilateral: false,
    baseExerciseId: null,
    variationType: null,
    equipmentDetail: null,
    muscleEmphasis: "peak",
    difficultyLevel: "beginner",
    requiresSpotter: false,
    riskFlags: [],
    ownerCoachId: null,
    instructions: null,
  },
  {
    id: "ex-calf-raise",
    name: "Panturrilha em pé",
    primaryMuscle: "calves",
    secondaryMuscles: [],
    equipment: "machine",
    movementPattern: "isolation",
    isUnilateral: false,
    baseExerciseId: null,
    variationType: null,
    equipmentDetail: null,
    muscleEmphasis: "peak",
    difficultyLevel: "beginner",
    requiresSpotter: false,
    riskFlags: [],
    ownerCoachId: null,
    instructions: null,
  },
];

const byId = new Map(EXERCISE_CATALOG.map((e) => [e.id, e]));

export function getExercise(id: string): Exercise | undefined {
  return byId.get(id);
}

export function getExercisesByMuscle(muscle: string): Exercise[] {
  return EXERCISE_CATALOG.filter((e) => e.primaryMuscle === muscle);
}

export function findSwapCandidates(exercise: Exercise): Exercise[] {
  return EXERCISE_CATALOG.filter(
    (e) =>
      e.id !== exercise.id &&
      e.primaryMuscle === exercise.primaryMuscle &&
      e.movementPattern === exercise.movementPattern,
  );
}
